### ISSUE TITLE
When if the system will shutdown ?

### ISSUE THREAD

**Issue by sauravmandal255** [My-Personal-HUB/AI_Jarvis#3]
Assign anyone for this @shivamkumar0611 @ayushii18  
Like saying good bye or bye or stop the system will stop 🤠

**Comment by sauravmandal255** [comment]
**Windows Shutdown Assistant helps to automatically shut down Windows in multiple modes. The basic way is to specify the time and make computer turn off at the fixed time. By configuring the settings, the program is able to repeat the task at a time or every day.**

**Comment by rohansahana6** [comment]
You can refer this 
Apple’s voice assistant Siri has been a talking point for many these days. It’s not because of any new feature that has been included in it but the Siri interactions and recordings of users that were unknowingly being heard by third-party contractors. When this issue was discovered, Apple confirmed that it has stopped this practice, which the company refers to as ‘Grading’. More recently, the Cupertino-based tech giant issued a formal apology and said that this will be optional in future and the recordings will be heard by Apple employees only, not third-party contractors. However, with the rising trust issues on voice assistants, it is natural to think of switching it off permanently. In case you are one of them and are still not convinced by Apple’s decision, here’s how you completely switch-off Siri from iPhones.

**Comment by ayushii18** [comment]
This issue has been solved by @rohansahana6 - https://github.com/My-Personal-HUB/AI_Jarvis/pull/8
